project:
  type: book
  output-dir: docs

book:
  title: "Utiliser R avec Quarto"
  subtitle: "Une introduction"
  author: "Sylvain Fiset, PhD"
  date: today
  sidebar:
    style: "floating"
    collapse-level: 2
  search: true
  chapters:
    - index.qmd
    - preface.qmd
    - a_propos_auteur.qmd
    - part: "Partie I"
      chapters:
      - introduction.qmd
      - R_RStudio.qmd
      - Extensions_R.qmd
      - Quarto.qmd
      - RStudio_options.qmd
      - RProject.qmd
      - Posit_cloud.qmd
    # - part: "Partie II"
    #   chapters:
    #   - Utiliser_Quarto.qmd
    #   - Metadonnees.qmd
    #   - Texte.qmd
    #   - Bloc_de_codes.qmd
    #   - ExempleR.qmd
    #   - Extract.qmd
    #   - Save_share.qmd
    #   - Problemes.qmd
    - part: "Partie III"
      chapters:
      - RProject_avance.qmd
    - references.qmd

bibliography: book0.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book
    toc: true
    toc-depth: 5
    number-sections: true
    colorlinks: true
    keep-tex: true
    code-line-numbers: true
    code-copy: true
    code-fold: false
    embed-resources: true
    css: include/webex.css
    include-after-body: include/webex.js    
    
editor: visual

_language: fr




