---
lang: fr
---

# Préface {-}

Pendant de nombreuses années, les étudiants qui suivaient mon cours _Introduction à la statistique appliquée en psychologie_ (ou sous différentes appellations) avaient comme consigne de rédiger leurs travaux à la main. Ils devaient donc transcrire de nombreuses formules, plus complexes les unes que les autres, et utiliser des tables statistiques pour tirer leurs conclusions. L'utilisation du logiciel [SPSS](https://www.ibm.com/ca-fr/products/spss-statistics/details) de IBM me satisfaisait pleinement comme complément à la compréhension de la matière. En plus de calculer à la main les différents tests statistiques, mes étudiants devaient vérifier, à l'aide de SPSS, si leurs calculs s'avéraient exacts (vérification qu'ils ne faisaient pas toujours, par manque de temps, me disait-on...).

Lors d'un récent congé sabbatique (l'un des privilèges associés au fait d'être professeur régulier au niveau universitaire...), je me suis inscrit à une formation de cinq jours offerte par [John Kruschke](https://jkkweb.sitehost.iu.edu/index.html), professeur de psychologie à l'[Université de l'Indiana](https://www.iu.edu/index.html) à Bloomington, sur les analyses bayésiennes. L'occasion de suivre une formation par l'un des maîtres incontestés des analyses bayésiennes m'enchantait. Par contre, la formation offerte par John Kruschke avait un prérequis obligatoire très important, soit celui d'être en mesure d'utiliser un logiciel qui m'était complètement inconnu à l'époque : R. N'ayant à ma disposition que le livre de John Kruschke [Doing Bayesian Data Analysis: A tutorial with R, JAGS, and Stan](https://sites.google.com/site/doingbayesiandataanalysis/what-s-new-in-2nd-ed) (et internet) pour apprendre R, je me suis lancé dans l'apprentissage autodidacte de ce logiciel. Oh, quelle aventure ! Il ne me restait que quelques mois entre mon inscription et cette formation. Avec l'enseignement de mes cours et la poursuite de mes travaux de recherche, le temps s'est écoulé très rapidement... Bien honnêtement, et malgré tous mes efforts, ma compréhension de R n'était pas à la hauteur de mes attentes lorsque j'ai finalement mis les pieds à Albuquerque, Nouveau-Mexique, dans la petite salle que je partageais avec John Kruschke et 15 autres personnes.

Fort heureusement, John Kruschke est un formateur exceptionnel et mes connaissances limitées de R ne m'ont pas empêchées d'apprendre à un rythme époustouflant les rudiments de base (et avancés) des analyses bayésiennes. Cette formation a changé mon congé sabbatique de façon radicale. En effet, le reste de mon année sabbatique fut consacré à approfondir ma compréhension de R et des analyses bayésiennes, tout en continuant de suivre de nombreuses formations en statistiques avancées. Au fond de moi, à mon retour de sabbatique, je jalousais le désir de substituer le logiciel SPSS par R pour l'enseignement de mon cours de statistiques. Ne vous méprenez pas. À l'époque, SPSS rencontrait parfaitement mes besoins. Avec une aisance déconcertante, mes étudiants apprenaient rapidement à insérer leurs données dans le chiffrier intégré de SPSS et à produire leurs analyses statistiques en cliquant sur les options des différents menus offerts par SPSS.

Mais pourquoi vouloir changer de logiciel, me direz-vous, si SPSS rencontrait mes exigences ? Le problème principal était un problème de licence. Voyez-vous, le coût d'une licence annuelle de SPSS est particulièrement élevé, surtout pour un étudiant. Bien entendu, la licence institutionnelle de l'université permettait à mes étudiant d'utiliser gratuitement SPSS à partir des ordinateurs mis à leur disposition, et ce, 24h sur 24 (si désiré...). Par contre, j'avais constaté deux choses. La première était que mes étudiants pirataient des codes d'accès à SPSS, ce qui leur permettait d'installer illégalement (et temporairement) SPSS directement sur leur ordinateur. La seconde était que lorsque mes étudiants quittaient le campus pour aller étudier dans d'autres institutions, SPSS n'était pas toujours disponible (certaines institutions et laboratoires de recherche utilisent STATA, SAS ou R). Leur apprentissage avec SPSS s'avérait pratiquement inutile, à moins, bien évidemment, qu'ils n'investissent de l'argent pour se payer une licence annuelle de SPSS, ce que peu d'entre eux étaient enclins à faire. 

R, étant gratuit, s'avérait donc pour moi une belle opportunité d'enseigner un logiciel statistique qui serait toujours disponible, peu importe où se retrouveraient mes étudiants pour compléter leurs études et leur formation[^pandémie]. Non, la substitution de SPSS par R en salle de classe ne fut pas facile... loin de là ! Et je remercie les premiers groupes d'étudiants qui ont dû subir cette transition : ils ont fait preuve d'une grande compréhension et d'une patience légendaire. Au cours des dernières années, j'ai été en mesure d'ajuster mon enseignement de manière à maximiser mon enseignement sur l'utilisation de R, la compréhension de la démarche statistique et l'interprétation des résultats. De plus, la rédaction des travaux, qui au départ se faisait à partir de captures d'écrans des résultats affichés dans la console de R, s'est transformée, avec la publication de l'application Quarto qui utilise le language rmarkdown, de manière à produire des documents complets, dynamiques, agréables à lire et facilement partageables. De mon point de vue, R, lorsque jumelé avec l'extension rmarkdown, permet une intégration complète de la démarche statistique[^STATA].

[^pandémie]: La substitution de SPSS par R me fut d'une grande utilité à l'hiver 2021 lorsque, en raison de la pandémie de la COVID-19, j'ai dû enseigner mon cours de statistiques à distance à tous mes étudiants. Ils n'ont eux qu'à télécharger R, en toute légalité.

[^STATA]: Notez que le logiciel STATA permet une intégration relativement similaire avec Microsoft Word. Mais, une licence perpétuelle étudiante de STATA coûte malgré tout quelque centaines de dollars...

Le présent document reflète donc mon expérience des dernières années avec l'enseignement de R et de l'utilisation du format R Notebook de l'extension rmarkdown pour R. Bien qu'aux premiers abords, R et R Notebook semblent intimidant, l'étudiant qui prend le temps de suivre la démarche et les exercices présentés ci-dessous sera en mesure de produire des documents de qualité dans le domaine des statistiques mais aussi dans n'importe quelle discipline.

Bonne lecture,

Sylvain
